#!/usr/bin/env bash
# Publish one JSON bundle per season as a GitHub Release asset.
#
# WHY: consumers (hoopR-nba-stats-data's impact build) can read this store two
# ways. Per-file over URL (raw.githubusercontent / a CDN) is right for an
# incremental refresh — a few thousand games. A FULL rebuild touches ~120k files,
# where per-file GETs are slow and rate-limit-prone; downloading ~30 season
# tarballs instead is one request per season. Extraction reconstitutes the exact
# store layout, so the consumer just points --raw-store-dir at the result and
# uses the ordinary filesystem path — no special-case reader.
#
# Archive paths are relative to nba_stats/json, i.e. {endpoint}/{season}/... , so
# every season extracts into ONE shared directory that is a valid store root.
#
#   bash scripts/publish_season_bundles.sh              # 1996:2026
#   bash scripts/publish_season_bundles.sh 2024:2026    # a sub-range
#   DRY_RUN=1 bash scripts/publish_season_bundles.sh    # build, don't upload
#
# Requires `gh` authenticated with write access to this repo.
set -uo pipefail

SEASONS="${1:-1996:2026}"
TAG="${BUNDLE_TAG:-nba-stats-raw-json}"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STORE="$REPO_DIR/nba_stats/json"
OUT_DIR="${BUNDLE_OUT_DIR:-$REPO_DIR/.bundles}"
DRY_RUN="${DRY_RUN:-0}"

cd "$REPO_DIR" || { echo "FATAL: cannot cd to $REPO_DIR" >&2; exit 1; }
[ -d "$STORE" ] || { echo "FATAL: no store at $STORE" >&2; exit 2; }
command -v gh >/dev/null || { echo "FATAL: gh CLI not found" >&2; exit 3; }

lo="${SEASONS%%:*}"; hi="${SEASONS##*:}"
mkdir -p "$OUT_DIR"

# GNU tar reads `host:path` in -f as a REMOTE archive, so a Windows drive-letter
# BUNDLE_OUT_DIR ("C:/...") would be parsed as host "C" and silently produce a
# broken bundle. --force-local disables that parsing; bsdtar (macOS) has neither
# the syntax nor the flag, so probe before using it.
TAR_LOCAL=""
if tar --force-local --version >/dev/null 2>&1; then TAR_LOCAL="--force-local"; fi

# One release holds every season's asset; create it once, idempotently.
if [ "$DRY_RUN" != "1" ] && ! gh release view "$TAG" >/dev/null 2>&1; then
  gh release create "$TAG" \
    --title "Raw stats.nba.com JSON — per-season bundles" \
    --notes "Per-season tarballs of nba_stats/json, paths relative to that directory.

Extract any number of seasons into one directory and pass it as a raw store root:

    tar -xzf nba_stats_json_2024.tar.gz -C \$STORE
    python -m nba_model_publish impact --seasons 2024 --raw-store-dir \$STORE

Regenerated by scripts/publish_season_bundles.sh; assets are replaced in place." \
    || { echo "FATAL: could not create release $TAG" >&2; exit 4; }
fi

built=0; skipped=0
for season in $(seq "$lo" "$hi"); do
  # A season lives in per-endpoint subdirs ({endpoint}/{season}/) plus bare
  # season files for unparameterized endpoints ({endpoint}/{season}.json).
  mapfile -t paths < <(cd "$STORE" && shopt -s nullglob && printf '%s\n' */"$season" */"$season".json)
  if [ "${#paths[@]}" -eq 0 ]; then
    echo "season $season: nothing in the store, skipping"; skipped=$((skipped + 1)); continue
  fi
  bundle="$OUT_DIR/nba_stats_json_${season}.tar.gz"
  # -C $STORE keeps archive paths store-relative so extraction is layout-exact.
  if ! tar $TAR_LOCAL -czf "$bundle" -C "$STORE" "${paths[@]}"; then
    echo "season $season: tar FAILED" >&2; continue
  fi
  size=$(du -h "$bundle" | cut -f1)
  echo "season $season: ${#paths[@]} paths -> $bundle ($size)"
  built=$((built + 1))
  # Upload per-file: a single multi-asset gh upload has silently dropped large
  # assets before. --clobber makes a re-run idempotent.
  if [ "$DRY_RUN" != "1" ]; then
    gh release upload "$TAG" "$bundle" --clobber \
      || echo "season $season: UPLOAD FAILED (bundle kept at $bundle)" >&2
  fi
done

echo "done: $built bundle(s) built, $skipped season(s) empty, tag=$TAG dry_run=$DRY_RUN"
